### ISSUE TITLE
Express JS ile backend server eklenmesi

### ISSUE THREAD

**Issue by itumekanik** [yukselir/ABC#1]
[express.js](https://expressjs.com/) adresinden takip ederek bir node.js backed server i yaratıp bu index.html i serve etmemiz gerek.

**Comment by yukselir** [comment]
-Hocam "http://localhost:3000" adresinde html i çalıştırdım işlem yapıyor. Fakat "http://localhost:3000/topla" adresinde "Cannot get /topla" hatasını alıyorum. 

-Ayrıca sayfaya css dosyası eklemek istedim. Aşağıdaki belirttiğim şekilde adresledim ancak external olarak çalıştıramadım. Ama internal olarak kullandığımda çalışıyor.

<img width="1440" alt="Screen Shot 2021-02-24 at 13 13 57" src="https://user-images.githubusercontent.com/52086896/108985768-7682df80-76a2-11eb-970a-119bd07222a3.png">

**Comment by itumekanik** [comment]
Browser address bardan yaptığın tüm istekler otomatik http "GET" istekleridir.
Express server tarafına bakarsan topla "POST" tipinden istek. O yüzden göremezsin. 

Detaylı bilgi için [Buraya Bakabilirsin](https://www.w3schools.com/tags/ref_httpmethods.asp)
