### ISSUE TITLE
Kafes sistem 2D python programlaması

### ISSUE THREAD

**Issue by itumekanik** [yukselir/ABC#10]
İki boyutlu sabit geometrili bir kafes sistemin datalarını alıp çözümü gönderen ve Normal kuvvetleri listelen bir program yazmamız gerekiyor.

**Comment by yukselir** [comment]
@itumekanik hocam python kodlarını bizimle paylaştığınız repl.it den aldım. Aşağıdaki gibi devam etmeyi düşünüyorum.
<img width="1440" alt="Screen Shot 2021-03-19 at 16 43 56" src="https://user-images.githubusercontent.com/52086896/111789774-92108d00-88d2-11eb-93ea-68de8b261657.png">

**Comment by itumekanik** [comment]
Gayet uygun @yukselir. Bu hafta görüşemedik. Rahatsızlandım biraz.  Önümüzdeki hafta konuşucaz. Sen  bir noktaya getir hızlaca bir meet yapar toparlarız.

**Comment by yukselir** [comment]
Tamamdır hocam, çok geçmiş olsun.

**Comment by yukselir** [comment]
**`Ks[cv_i, cv_j] += Ks[cv_i, cv_j] + Ke[i, j]`** ==>  **`Ks[cv_i, cv_j] += Ke[i, j]`**
- Hocam @itumekanik, system stiffness matrix de burayı gözden kaçırmışız, onarıldı.

**Comment by itumekanik** [comment]
> **`Ks[cv_i, cv_j] += Ks[cv_i, cv_j] + Ke[i, j]`** ==> **`Ks[cv_i, cv_j] += Ke[i, j]`**
> 
> * Hocam @itumekanik, system stiffness matrix de burayı gözden kaçırmışız, onarıldı.

Düzeltip pushla istersen @yukselir

**Comment by yukselir** [comment]
@itumekanik bu issue tamamlandı sanırım, kapatayım mı hocam.

**Comment by itumekanik** [comment]
Gayet iyi @yukselir . Kapatıyorum.
