### ISSUE TITLE
Kafes sistemin grafik olarak çizilmesi (dinamik grafik)

### ISSUE THREAD

**Issue by itumekanik** [yukselir/ABC#13]
Selam @yukselir . Yeni görevimiz kafes sistemin girilen parametrelere göre çizilmesi ve sonuç diagramların elemanlar üzerinde gösterilmesi. Zor bir görev ama çok şey öğretecek.

Bunun için https://dmitrybaranovskiy.github.io/raphael/  bu kütüphane fena değil başlangıç olarak.

Öncelikle kütüphaneyi sayfada basit bir çizim yapabilecek şekilde setup ını yapman gerek. Sonrası kolay. 

Yani branch açmayı ve publish etmeyi unutma.

**Comment by yukselir** [comment]
@itumekanik, hocam  python da oluşturduğumuz us array e html den nasıl erişebilirim.

**Comment by itumekanik** [comment]
Selam @yukselir. axios requestinin dönüş parametrelerini ayarladım. Aşağıdaki resimde var. Artık çizim için gerekli olabilecek tüm nod ve eleman datalarını dönüyor. Normal kuvvetleri random sayılar olarak yolladım. Gerçek kuvvetler için sen güncellerisin python kısmını. Bu dataları "res.data" dan alıp buna göre çizim yapman gerek. Zorlanırsan haber ver.

![image](https://user-images.githubusercontent.com/31310412/114375928-d91a3700-9b8d-11eb-9f13-e93fbf96f654.png)

**Comment by yukselir** [comment]
@itumekanik hocam (res.data) dan verileri çekmek için array metodları denedim ama yapamadım.

<img width="1051" alt="Screen Shot 2021-04-22 at 22 57 56" src="https://user-images.githubusercontent.com/52086896/115777682-457f0c80-a3be-11eb-9930-83a8fe58eeaa.png">

**Comment by itumekanik** [comment]
Selam @yukselir .

Vue nun data() metoduna elements= null ve nodes=null diye bir değişken tanımla. 

Sonra da 

```
this.elements = res.data.payload.elements;
this.nodes = res.data.payload.nodes;
```

ile veriyi vue metotları içinde kullanılabilir hale getirmiş olursun.
Sonra da bir draw() metodu içinde veriyi kullanabilirsin.

```
methods : {
   draw : function () {
           //this.elements ve this.nodes u burada kullanıp çizgileri çizdirebilirsin.........
           //pazar konuşalım.
   }
}

```

**Comment by yukselir** [comment]
<img width="1022" alt="Screen Shot 2021-04-28 at 20 31 12" src="https://user-images.githubusercontent.com/52086896/116447639-e22f2780-a860-11eb-8099-9fef54c7226b.png">

**Comment by yukselir** [comment]
- Hocam @itumekanik, çizimler jsxGraph ile değiştirildi ama grafiği kutuya göre ölçeklendirmeyi yapamadım. Müsait olduğunuz bir vakit görüşebilir miyiz.

**Comment by itumekanik** [comment]
> * Hocam @itumekanik, çizimler jsxGraph ile değiştirildi ama grafiği kutuya göre ölçeklendirmeyi yapamadım. Müsait olduğunuz bir vakit görüşebilir miyiz.

Selam @yukselir . Güncelleme yaptım. Bu aralar dersler falan epey sıkıştı işler. Müsait olunca arayacağım.
