### ISSUE TITLE
.gitignore dosyası eklenmesi

### ISSUE THREAD

**Issue by yukselir** [yukselir/ABC#5]
- Hocam MergeDeneme1 klasöründeki dosyaları github a yeni bir branch olarak eklemek istiyorum. node_modules ve .gitignore dosyalarını ekleyemedim. Üzerinde çalşıyorum.
<img width="617" alt="Screen Shot 2021-02-25 at 00 23 32" src="https://user-images.githubusercontent.com/52086896/109067568-bcba5c00-76ff-11eb-9ff0-bbc07722c3f1.png">

**Comment by yukselir** [comment]
Tamamlandı ve master branch olarak eklendi.

**Comment by itumekanik** [comment]
.gitignore dosyası önemli.  node_modules ü muhakkak gitignore a eklemek gerekiyor aksi taktirde tüm node_modules github a gelir :D

**Comment by itumekanik** [comment]
Konuyu çözdüysen issue yu kapatayım

**Comment by yukselir** [comment]
Kapatabiliriz hocam.
