### ISSUE TITLE
Ortam değişkenlerinin ayarlanması

### ISSUE THREAD

**Issue by itumekanik** [yukselir/ABC#7]
https://www.npmjs.com/package/convict

Bu paket ile programın çalıştığı shell in ortamındaki değişkenler çok sistematik şekilde kod a aktarılabiliyor.

Araştırıp uygulamak lazım. Öncelikle python path falan gibi yapıları bu paketle tanımlayıp içe aktarmayı dene.

**Comment by yukselir** [comment]
Hocam convict paketini ekledim, çalışır durumda.

**Comment by itumekanik** [comment]
@yukselir burada yaptığın commit i mention larsan daha hızlı ulaşırım.  #1  gibi mesela. Git commit yaparken de #1 gibi issue numarasını yazarsan otomatik olarak mentionlar.

**Comment by yukselir** [comment]
@itumekanik ilk yazdığımda çalışmıştı fakat daha sonradan çalıştıramadım. Sizde çalışıyor mu acaba bir ara kontrol eder misiniz.

**Comment by itumekanik** [comment]
> @itumekanik ilk yazdığımda çalışmıştı fakat daha sonradan çalıştıramadım. Sizde çalışıyor mu acaba bir ara kontrol eder misiniz.

convict i uygulama şeklin hatalı. Bir ara beraber bakmamız lazım.
