### ISSUE TITLE
geliştirici lokalde ortam değişkenlerinin ayarlanması

### ISSUE THREAD

**Issue by itumekanik** [yukselir/ABC#9]
https://www.npmjs.com/package/dotenv

Bu paket lokaline oluşturduğun .env dosyasından ortam değişkenlerini processin içine otomatik olarak alıyor.

Environmentla ilgili son işimiz bu. Böylece örneğin pythonPath sende ve bende farklı olabilecek.

**Comment by yukselir** [comment]
@itumekanik hocam bu görev tamamdır ama aklıma bir soru takıldı. Convict paketini kullanmadan sadece Env dosyası oluşturup pythonPath i oradan direkt çağırdığımda çalışmıştı. Burada convict e neden ihtiyacımız var.

**Comment by itumekanik** [comment]
- Birincisi convict ortam değişkenlerinin validasyonunuda yapıyor. Örneğin ortam değişkeni bir url ise gerçekten url verilip verilmediğini de kontrol ediyor.
- İkincisi ortam değişken adları (örn: PYTHON_PATH) ile custom verilen isimler arasında (örneğin pythonPath) otomatik ilişki kuruyor. Böylece programın içinde PYTHON_PATH=== "/usr/bin/python" gibi kontroller yerine;
```js
const pythonPath = config.get("pythonPath");
```

şeklinde temiz kod yazmış oluyoruz. CI/CD ciler  PYTHON_PATH ile ilgilenirler. Programcılar pythonPath ile.
Herhangi bir anda CI/CD ci  PYTHON_PATH değil de PYTHON_PROCESS_PATH olsun diye bir değişiklik talep ederse programın içindeki kodları değiştirmek yerine convict in parametresini değiştiriyoruz sadece.
